[build]
    command = "npm run build"
    publish = "build/"

[context.production.environment]
    REACT_APP_ENV = "PRODUCTION"

[context.branch-deploy.environment]
    REACT_APP_ENV = "BRANCH_DEPLOY"

[context.deploy-preview.environment]
    REACT_APP_ENV = "REVIEW_APP"